language: php
php:
    - '7.1'

services:
  - mysql

env:
    - DB=mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
    
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS tine20 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" -uroot; fi
  - git clone https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM.git tine20
  - composer install -d tine20/tine20
  - rm -rf tine20/tine20/vendor/zendframework/zendframework1/library
  - mv library tine20/tine20/vendor/zendframework/zendframework1/
  - cd tine20/tine20
  - cp config.inc.travis.php config.inc.php
  - cp install.properties.travis install.properties
  - vendor/bin/phing tine-install

script:
  - cd ../tests/tine20
  - ../../tine20/vendor/bin/phpunit --color TravisTests.php
